package chiefnavigator.quest;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

/** Headless checks for save-safe, creation-only Odyssey jump topology. */
public final class OdysseyJumpPointRepairRegression {
    private static void check(boolean condition, String message) {
        if (!condition) throw new AssertionError(message);
    }

    private static Path findSource() {
        Path source = Paths.get(
                "src", "chiefnavigator", "quest", "OdysseyExpanseSystem.java");
        if (Files.isRegularFile(source)) return source;
        source = Paths.get(
                "..", "src", "chiefnavigator", "quest",
                "OdysseyExpanseSystem.java");
        if (Files.isRegularFile(source)) return source;
        throw new IllegalStateException(
                "Could not locate OdysseyExpanseSystem.java");
    }

    private static String methodBody(String source, String signature) {
        int start = source.indexOf(signature);
        check(start >= 0, "Could not locate " + signature);
        int open = source.indexOf('{', start);
        check(open >= 0, "Could not locate body for " + signature);
        int depth = 0;
        for (int index = open; index < source.length(); index++) {
            char ch = source.charAt(index);
            if (ch == '{') depth++;
            if (ch == '}' && --depth == 0) {
                return source.substring(start, index + 1);
            }
        }
        throw new AssertionError("Unterminated body for " + signature);
    }

    public static void main(String[] args) throws Exception {
        String[] systemIds = {
            OdysseyExpanseSystem.SYSTEM_ID,
            OdysseyExpanseSystem.MESSINA_ID,
            OdysseyExpanseSystem.SILENT_WAKE_ID,
            OdysseyExpanseSystem.ASHEN_VERGE_ID,
            OdysseyExpanseSystem.LAST_LIGHT_ID,
            OdysseyExpanseSystem.DEVOURED_REACH_ID
        };
        int total = 0;
        for (String systemId : systemIds) {
            int count = OdysseyExpanseSystem
                    .getAuthoredHyperspaceEndpointCount(systemId);
            check(count == (OdysseyExpanseSystem.DEVOURED_REACH_ID.equals(
                            systemId) ? 1 : 3),
                    systemId + " has the wrong authored route count");
            total += count;
        }
        check(total == 16,
                "Odyssey Sector must expose exactly 16 ordinary endpoints");

        String source = new String(
                Files.readAllBytes(findSource()), StandardCharsets.UTF_8);
        String ensure = methodBody(
                source, "public static StarSystemAPI ensureExists()");
        int existingReturn = ensure.indexOf("return existing;");
        int creation = ensure.indexOf("createGeneratedNebula()");
        int jumpConfiguration = ensure.indexOf("configureClusterJumpPoints(");
        check(existingReturn >= 0 && creation > existingReturn
                        && jumpConfiguration > creation,
                "Serialized Odyssey systems must return before topology creation");

        String implementation = methodBody(source,
                "private static void configureClusterJumpPoints(");
        check(implementation.contains("findExistingHyperspaceEndpoint("),
                "Fresh generation must retain engine-created endpoint identity");
        check(implementation.contains(
                        "system.autogenerateHyperspaceJumpPoints(true, false, false)"),
                "Fresh generation must retain vanilla endpoint creation");
        check(implementation.contains("rediscoverClusterGravityWells("),
                "Fresh generation must retain serialized body wells");
        check(implementation.contains("campaign as-is instead of rebuilding it"),
                "Incomplete generation must fail conservatively");

        check(!implementation.contains("removeTrackedHyperspaceAccess("),
                "Jump creation must not delete tracked engine endpoints");
        check(!implementation.contains("removeLegacyManualHyperspaceAccess("),
                "Jump creation must not prune legacy serialized endpoints");
        check(!implementation.contains("removeSurplusLocalJumpPoints("),
                "Jump creation must not prune local serialized endpoints");
        check(!implementation.contains("removeSurplusClusterAccess("),
                "Jump creation must not prune serialized access");
        check(!implementation.contains("ensureClusterHyperEndpoint("),
                "Jump creation must not manually replace engine endpoints");
        check(!implementation.contains("ensureClusterGravityWells("),
                "Jump creation must not replace body-well objects");
        check(!implementation.contains("getAutogeneratedJumpPointsInHyper("),
                "Transient autogenerated endpoint lists are not authoritative");
        check(!implementation.contains("getAutogeneratedNascentWellsInHyper("),
                "Transient autogenerated well lists are not authoritative");
        check(!implementation.contains(".removeEntity("),
                "Jump creation must never delete campaign entities");
        check(!implementation.contains("rebuildPass"),
                "Jump creation must not expose a load-time rebuild path");

        System.out.println("Odyssey jump-point lifecycle regression passed.");
    }
}
